### ISSUE TITLE
create-csv issue 

### ISSUE THREAD

**Issue by blueciren** [blueciren/correspondence#1]
Dear David, 
1) I tried to create a "date" column for the Cytoscape in order to create multiple edges, based on the number of the letters. I noticed that without the function to put "", the sequences themselves does not work. e.i. <xsl:sequence select="kiun:quote(@date)"/> If I remove "" function, the error message says "F cannot create an attribute node whose parent is a document node. Most recent element start tag was output at line -1 of module unknown." I think I did not fully understand your explanation. I am sorry but could you explain why does this happen? 

2) If I use this sequence (<xsl:sequence select="kiun:quote(//year[descendant::letter[@addressee]]/@id)"/>) to indicate only a year, the oxygen says that "a sequence of more than one item is not allowed as the first argument of kiun:quote()." It seems like the sequence brings multiple "years," which I could not understand. Doesn't this sequence indicate @id of each letter's parent-year?

**Comment by djbpitt** [comment]
@blueciren If I’ve understood correctly that the XSLT you are developing is *create-csv2.xsl* (it would help me find the code you want me to look at if you could please specify the XSLT filename and location when you open this kind of issue), I ran that against *dostoevsky_letters.xml* and it output the dates for each letter as an additional field, which I think is what you ask about: a “date” column, with a date for each letter. 

In your \#1, above, you write `kiun:quote(@Date)`, with an uppercase “D”, and since there is no attribute `@Date`, with an uppercase “D”, that cannot return anything. But your *create-csv2-xsl* correctly uses lowercase “d”, and that does find and output the date.

The error message, which you reproduce in your original issue, tells you why your \#2 (`kiun:quote(//year[descendant::letter[@addressee]]/@id)`) doesn’t work. You are returning multiple year `@id` attributes, and the `kiun:quote()` function accepts only a single string as input. But what do you want that statement to return? That is, what would the desired CSV look like? You are asking for the `@id` values of all years that contain letters that have an `@addressee`, all at once, as a single sequence. But your CSV outputs one line per letter, so I don’t understand where you would want to put a single sequence of all years in the corpus.

**Comment by blueciren** [comment]
I am sorry that I did not articulate the issue clear enough. 
For #1, I found something strange here. I wrote @date with small letter d, but in "preview" and when I click "comment", it automatically changes into capital letter D. So 'D' was a technical issue here. Seemingly they do this for the specific word date? 
I originally wrote it with a small letter d. Without ""(which means the function of "kiun:quote()") the sequence of select="@date" or "@addressee does not work. It produces nothing in the output on the right. With the function, everything works fine. So I wanted to know in detail how it worked and not worked. 
For #2, I intended to return the year each letter is written. I thought the sequence would work in <xsl:for-each>: to find an attribute of @id of year element while processing each letter (since id (a value of the year) is an attribute of parent element year). I wanted to create CSV with one more column that indicates a year or specific date when each letter is written (in order to "weigh" edges in Cytoscape). After the failure to bring @id of years, I decided to bring @date of letter to return the whole date  in _create-csv2.xsl_. Seemingly I misunderstood the logic of the whole sequence from the beginning. I thought if  <xsl:sequence select="kiun:quote(@addressee)"/> works, then the sequence above would work in a similar way....

**Comment by djbpitt** [comment]
@blueciren Sorry for the long delay in responding! 

I think the issue with your question 1 is, as the error message you reported says, that you cannot create an attribute node as a child of a document node (attribute nodes can only be children of element nodes). When you write `select="@data"`, you are asking not for the attribute *value* (what a human thinks of as the text of the date), but for the attribute *node*. Your `kiun:quote()` function returns a string, that is, when you pass it the `@date` attribute, it converts it to a string, wraps quotation marks around it, and sends it back as a string (that is, the quoted date is now a string, and no longer an attribute node). You can create a string as a child of a document node, so writing the output of the function is okay. If you want to create a string without quotes, you can do that with the XPath `string()` function, e.g., `select="@date ! string(.)"`. You can read about the `!` operator at <https://www.w3.org/TR/xpath-31/#id-map-operator> (see the examples especially).

Your question 2 tries to process multiple years at once (raising an error because `kiun:quote()` can process only one item at a time, and not a sequence of multiple items) because when you write:

```xml
select="kiun:quote(//year[descendant::letter[@addressee]]/@id)"
```

you begin the XPath path expression inside the parentheses with `//`. That means “go to the document node and look at all of its descendants”—that is, it means to find all `<year>` elements in the entire document. You then filter all of the years to keep only the ones that have a `<letter>` descendant with an `@addressee` and an `@id`. Since there are a lot of letters that have `@addressee` and `@id` attributes, your pattern, even after that filtering, still matches multiple items, and you can’t pass multiple items to your `kiun:quote()` function.

If you want just one year, the year of the letter you are looking at the moment, you need to ask for the `<year>` parent of the current letter. Try, from inside the `<xsl:for-each>` that processes all of the letters:

```xml
select="kiun:quote(../@id)"
```

This says to start from the current context (a single letter at a time), go up to its parent (which will be a `<year>`), and get the `@id` attribute of that `<year>`. If you don’t want to quote the year, since it’s an attribute, you’ll have to convert it to a string:

```xml
select="../@id ! string(.)"
```

Please let me know if this helps!

**Comment by blueciren** [comment]
Thank you for your reply, David.
To tell the truth, this month I could not find time to work on the Cytoscape project because of the job application, article submission(s), the driving lessons, all the house chores & caring for my mom, and additionally, the preparation for the two courses for the fall term. Whenever I have time, I will get back to this work. I had plenty of plans, but this lovely summer, when I could freely enjoy this jobless-ness is just gone....

Best,
Kiun
________________________________
